import { describe, expect, it } from 'vitest';
import { svgBody, themeSvg } from '@tmc/render';

const GRAPHVIZ_PROLOG = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 12.0.0 -->
<!-- Title: G Pages: 1 -->
`;

const DOC = `${GRAPHVIZ_PROLOG}<svg width="100pt" height="50pt"><g class="node"><title>a</title></g></svg>`;

describe('svgBody', () => {
  it('drops everything before the svg element', () => {
    const body = svgBody(DOC);
    expect(body.startsWith('<svg')).toBe(true);
    expect(body).not.toContain('<?xml');
    expect(body).not.toContain('<!DOCTYPE');
    expect(body).not.toContain('Generated by graphviz');
    expect(body.endsWith('</svg>')).toBe(true);
  });

  it('keeps the whole element, including its own comments', () => {
    // Comments inside the element are valid where this ends up, and rewriting the
    // interior is what made the previous implementation unsound.
    const body = svgBody(`${GRAPHVIZ_PROLOG}<svg><!-- keep me --><g/></svg>`);
    expect(body).toContain('<!-- keep me -->');
  });

  it('returns nothing when handed something that is not an svg', () => {
    expect(svgBody('just some text')).toBe('');
    expect(svgBody('')).toBe('');
  });

  it('is not fooled by the word svg appearing earlier', () => {
    const body = svgBody(`<!-- about svgs in general --><svg id="real"/>`);
    expect(body).toBe('<svg id="real"/>');
  });

  /**
   * The two CodeQL findings this replaced, as tests.
   *
   * js/incomplete-multi-character-sanitization: deleting `<!-- ... -->` in one pass
   * can splice the neighbours into a fresh `<!--`, so the pass does not converge.
   * js/polynomial-redos: the lazy `[\s\S]*?` scans backtrack quadratically.
   */
  it('cannot be made to emit a comment opener by splicing', () => {
    const body = svgBody(`<svg><text><!-<!-- -->-</text></svg>`);
    // Whatever the interior says, the output is the element verbatim; nothing was
    // rewritten, so nothing new can be constructed by rewriting.
    expect(body).toBe('<svg><text><!-<!-- -->-</text></svg>');
  });

  it('handles adversarial input in linear time', () => {
    const hostile = `${'<?xml '.repeat(60_000)}<svg id="x"/>`;
    const started = performance.now();
    const body = svgBody(hostile);
    const elapsed = performance.now() - started;
    expect(body).toBe('<svg id="x"/>');
    // The old implementation took seconds on inputs this shape.
    expect(elapsed).toBeLessThan(500);
  });

  it('handles a long run of whitespace before the element', () => {
    const started = performance.now();
    svgBody(`${' '.repeat(500_000)}<svg/>`);
    expect(performance.now() - started).toBeLessThan(500);
  });
});

describe('themeSvg', () => {
  it('inserts the theme block after the opening tag', () => {
    const themed = themeSvg('<svg width="10"><g/></svg>');
    expect(themed).toContain('prefers-color-scheme');
    expect(themed.indexOf('<style>')).toBeGreaterThan(themed.indexOf('<svg'));
    expect(themed.indexOf('<style>')).toBeLessThan(themed.indexOf('<g/>'));
  });

  it('leaves a non-svg document alone', () => {
    expect(themeSvg('not an svg')).toBe('not an svg');
  });
});
