#!/usr/bin/env node
/**
 * Bundle the YAML data files into TypeScript modules.
 *
 * Two reasons this exists. The published packages used to locate `data/` and
 * `rules/` by walking relative to the compiled output, which breaks the moment a
 * bundler moves the code or a consumer vendors it. And the browser has no
 * filesystem at all, so the editor could not otherwise see the technology catalogue
 * or the built-in rules.
 *
 * The YAML remains the source of truth and stays readable and reviewable in a pull
 * request; this only mirrors it. Run `npm run generate` after editing either.
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

const BANNER = `// Generated by scripts/generate-data.mjs. Do not edit.
// Source of truth is the YAML it was built from; run \`npm run generate\` to refresh.
/* eslint-disable */
`;

function write(path, contents) {
  mkdirSync(dirname(path), { recursive: true });
  const next = BANNER + contents;
  const current = existsSync(path) ? readFileSync(path, 'utf8') : '';
  if (current === next) return false;
  writeFileSync(path, next, 'utf8');
  return true;
}

/** Stable key order, so a regeneration produces no spurious diff. */
function stableStringify(value) {
  return JSON.stringify(value, (_key, v) => {
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      return Object.fromEntries(Object.entries(v).sort(([a], [b]) => a.localeCompare(b)));
    }
    return v;
  }, 2);
}

// --- catalogue --------------------------------------------------------------

const dataDir = join(ROOT, 'packages/core/data');
const technologies = parseYaml(readFileSync(join(dataDir, 'technologies.yaml'), 'utf8'));
const protocols = parseYaml(readFileSync(join(dataDir, 'protocols.yaml'), 'utf8'));

const catalogChanged = write(
  join(ROOT, 'packages/core/src/generated/catalog-data.ts'),
  `import type { RawCatalogData } from '../catalog-core.js';

export const BUILTIN_CATALOG_DATA: RawCatalogData = ${stableStringify({
    technologies: technologies.technologies,
    protocols: protocols.protocols,
  })} as const satisfies RawCatalogData;
`,
);

// --- rules ------------------------------------------------------------------

const rulesDir = join(ROOT, 'packages/rules/rules');
const ruleFiles = readdirSync(rulesDir)
  .filter((name) => name.endsWith('.rule.yaml') || name.endsWith('.rule.yml'))
  .sort();

const ruleDocuments = [];
for (const name of ruleFiles) {
  const parsed = parseYaml(readFileSync(join(rulesDir, name), 'utf8'));
  const docs = Array.isArray(parsed?.rules) ? parsed.rules : [parsed];
  for (const doc of docs) ruleDocuments.push({ file: name, doc });
}

const rulesChanged = write(
  join(ROOT, 'packages/rules/src/generated/rule-data.ts'),
  `/** Every built-in rule, with the file it came from so \`explain\` can cite it. */
export interface RawRuleEntry {
  readonly file: string;
  readonly doc: unknown;
}

export const BUILTIN_RULE_DATA: readonly RawRuleEntry[] = ${stableStringify(ruleDocuments)};
`,
);

const summary = [
  `technologies: ${Object.keys(technologies.technologies).length}`,
  `protocols: ${Object.keys(protocols.protocols).length}`,
  `rules: ${ruleDocuments.length}`,
].join(', ');

console.log(
  `generated ${summary}${catalogChanged || rulesChanged ? '' : ' (no change)'}`,
);

// In CI, a stale generated file means someone edited YAML without regenerating.
if (process.argv.includes('--check') && (catalogChanged || rulesChanged)) {
  console.error(
    '\nGenerated data was out of date and has been rewritten.\n' +
      'Run `npm run generate` and commit the result.',
  );
  process.exit(1);
}
